config/routes.rb
PsArt::Application.routes.draw do
  resources :users, except: :show
  resources :pieces

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  root to: 'home#index'
end

app/models/piece.rb
class Piece < ActiveRecord::Base
  attr_accessible :name, :lat, :lng, :gmaps, :address

  acts_as_gmappable :lat => 'lat', :lng => 'lng', :process_geocoding => :geocode?,
                  :address => "address", :normalized_address => "address",
                  :msg => "Sorry, not even Google could figure out where that is"

  def geocode?
    (!address.blank? && (lat.blank? || lng.blank?)) || address_changed?
  end

  def gmaps4rails_infowindow
    "<h3>#{self.name}</h3><br><a href=\"/pieces/#{self.id}\">Click for details</a>"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation

  validates :name, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize

  protect_from_forgery

  protected
    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, notice: 'Please log in'
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  def index
    @markers = Piece.all.to_gmaps4rails
  end

  def new
    @piece = Piece.new
  end

  def edit
    @piece = Piece.find_by_id(params[:id])
  end

  def show
    @piece = Piece.find_by_id(params[:id])
  end

  def create
    @piece = Piece.new(params[:piece])

    if @piece.save
      redirect_to @piece, notice: 'Piece was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @piece = Piece.find_by_id(params[:id])

    if @piece.update_attributes(params[:piece])
      redirect_to @piece, notice: 'Piece was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @piece = Piece.find_by_id(params[:id])
    @piece.destroy

    redirect_to pieces_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:user_name] = user.name
      redirect_to pieces_path
    else
      redirect_to login_url, alert: "Invalid name/pw!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>PsArt</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "ps_Art", '/', class: 'brand' %>
      <div class="nav-collapse collapse">
        <p class="navbar-text pull-right">
          <% if session[:user_id] %>
            Logged in as <%= session[:user_name] %> <%= link_to 'Log out', logout_path, method: :delete %>
          <% else %>
            <%= link_to 'Log in', login_url %>
          <% end %>
        </p>
        <ul class="nav">
          <li><%= link_to 'Pieces', pieces_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>
<div class="container">
  <%= yield %>
</div>

<%= yield :scripts %>

</body>
</html>

app/views/pieces/_form.html.erb
<%= form_for(@piece) do |f| %>
  <% if @piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@piece.errors.count, "error") %> prohibited this piece from being saved:</h2>

      <ul>
      <% @piece.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br />
    <%= f.text_field :lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pieces/edit.html.erb
<h1>Edit piece</h1>

<%= render 'form' %>

<%= link_to 'Back', pieces_path %>

app/views/pieces/index.html.erb
<div class="row">
  <div class="span12">
    <div class="hero-unit">
      <h1>TC Project</h1>
      <p>Bass Museum of Art<p>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12">
    <%= gmaps4rails(@markers) %>
  </div>
</div>
<div class="row">
  <div class="span12">
    <p><%= link_to 'Add', new_piece_path %></p>
  </div>
</div>

app/views/pieces/new.html.erb
<h1>New piece</h1>

<%= render 'form' %>

<%= link_to 'Back', pieces_path %>

app/views/pieces/show.html.erb
<div class="row">
  <div class="span12">
    <div class="hero-unit">
      <h1><%= @piece.name %></h1>
      <p>
        <%= link_to 'Edit', edit_piece_path %> |
        Remove
      </p>
    </div>
  </div>
</div>
<div class="row">
  <div class="span6">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce aliquam quam vel turpis pulvinar consequat. Pellentesque sodales, neque vitae cursus facilisis, urna elit ullamcorper enim, vestibulum viverra odio nulla in lorem. Aenean non sapien libero, sit amet rutrum sem. Aliquam convallis turpis malesuada neque suscipit et bibendum lorem vestibulum. Mauris orci augue, mollis ut accumsan non, semper sit amet nulla. Nulla iaculis lacus non odio scelerisque congue. Donec ultrices interdum purus, eu facilisis eros sollicitudin at. Praesent ornare purus vitae nunc pretium semper. Sed laoreet vulputate interdum. Nulla sed lacus sed felis aliquam accumsan sed at justo. Morbi placerat est quis odio egestas volutpat. Quisque sit amet lectus eu ante dignissim varius. Curabitur sollicitudin placerat eros id tincidunt. Fusce tincidunt dolor a turpis posuere placerat bibendum eros scelerisque. Fusce lobortis est eget justo fringilla semper. Sed tempor, quam in egestas mattis, ipsum elit mollis leo, nec semper felis erat sed libero.</p>

    <p>Nullam ipsum elit, venenatis non cursus lobortis, laoreet in lectus. Ut egestas metus in dolor laoreet lacinia. Praesent a arcu in est tristique malesuada. Phasellus luctus consequat mollis. Integer neque quam, lobortis in cursus non, suscipit a magna. Aliquam at urna lectus, ut egestas neque. Mauris vitae arcu enim. Nulla facilisi. Etiam rutrum commodo nisl in lobortis. Phasellus a risus a justo lacinia tincidunt. Suspendisse et nulla ipsum. Quisque pretium volutpat lectus, molestie dignissim risus dapibus vel. Ut venenatis luctus leo vel convallis.</p>

    <p>Nam a lectus sem, eu elementum eros. Mauris eleifend consectetur lobortis. Vestibulum dictum, nunc non posuere tempus, metus risus mollis lorem, a condimentum mi justo et risus. Nullam rutrum lectus eu diam luctus tempus. Ut in odio vel nunc cursus ultrices. Ut leo nulla, aliquam vel vestibulum sit amet, elementum quis erat. Donec malesuada, purus ut commodo convallis, tellus est dignissim enim, ornare sagittis libero purus quis neque. Curabitur sit amet mauris leo, quis eleifend mi. Sed augue turpis, bibendum sed malesuada eget, viverra eget mauris. Duis faucibus mattis tempus.</p>

    <p>Aenean mattis enim quis enim gravida aliquam. Sed pharetra imperdiet orci. Sed id quam nulla. Ut ullamcorper, dui eget volutpat hendrerit, metus dolor laoreet mauris, ac lobortis massa nunc sed odio. Suspendisse sit amet nunc vel metus vulputate tincidunt vitae id turpis. Etiam ante odio, fringilla ac pellentesque ut, facilisis in enim. Nunc augue ipsum, dignissim a imperdiet eget, iaculis a urna. Maecenas ante lacus, lacinia quis dictum id, molestie sit amet diam. Proin tincidunt augue ut justo aliquet tempor. Praesent blandit suscipit venenatis.</p>

    <p>Suspendisse viverra tempor felis, quis mattis ligula fermentum at. Sed non turpis eget lectus vehicula mattis. Suspendisse potenti. In tempor odio non orci euismod vestibulum. Sed nec libero dui. Quisque sit amet pretium tellus. Aliquam erat volutpat. Sed mauris lectus, cursus ac porta quis, tincidunt in metus. Integer sodales sollicitudin tellus, sit amet lobortis augue interdum sit amet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce vehicula quam non nibh cursus lacinia.</p>
  </div>
  <div class="span6">
    <div pub-key="pub-a06a2405-a276-4f1b-91ce-5bb78d0f3431" sub-key="sub-07da764a-ff98-11e1-9510-d18d7b6ca35d" ssl="off" origin="pubsub.pubnub.com" id="pubnub"></div>
    <div class="blurbs-box">
      <div class="input-box">
        <textarea class="input-xlarge span6" name="new-message" id="message-field" placeholder="Type a message..." rows="3"></textarea>
      </div>
      <br>
      <div class="convo-box">
        
      </div>
    </div>
  </div>
</div>

<style>
  .message-sender{
    font-weight: bold;
  }
  .message-date{
    font-size: 90%;
    margin-right: 0.5em;
    font-style: italic;
  }
</style>
<script src="http://cdn.pubnub.com/pubnub-3.1.min.js"></script>
<script>(function(){
  // Channel to be provided by CaseBlurb db. Probably use case_id.
  var channel = "<%= @piece.name %> <%= @piece.lat.to_s %>";
  // Provide username too for posting to convo box:
  var user = "<%= session[:user_name]%>";
  var msgBox = $('#message-field');
 
    // LISTEN FOR MESSAGES
    PUBNUB.subscribe({
        channel    : channel,      // CONNECT TO THIS CHANNEL.
 
        restore    : false,              // STAY CONNECTED, EVEN WHEN BROWSER IS CLOSED
                                         // OR WHEN PAGE CHANGES.
 
        callback   : function(message) { // RECEIVED A MESSAGE.
            $('.convo-box').prepend('\
            <div class = "well">\
              <div class="row-fluid">\
              <span class="message-sender">'+message.sender+'</span>\
              <span class="message-date pull-right"><%= Time.now %></span>\
              </div>\
              <div class="row-fluid">\
              <span class="message-text">'+message.text+'</span>\
              </div>\
            </div>')
        },
 
        disconnect : function() {        // LOST CONNECTION.
            $('.convo-box').prepend(
                "<div class=\"well\">\
                  Error: Connection Lost." +
                  "Will auto-reconnect when Online.\
                </div>"
            )
        },
 
        reconnect  : function() {        // CONNECTION RESTORED.
            $('.convo-box').append("Connection restored!")
        },
 
        connect    : function() {        // CONNECTION ESTABLISHED.
 
            PUBNUB.publish({             // SEND A MESSAGE.
                channel : channel,
                message : {sender: '[Announcement]', text: user + " is now online.", date: '[date]'}
            })
 
        }
    })
    
    $('#message-field').keyup(function(e) {
    if((e.which) === 13){
      PUBNUB.publish({
        channel : channel, 
        message : {sender: user,
          text: msgBox.val(),
          date:'[date]'
        },
        callback: function(resp){
          msgBox.val('');
        }
      });
    }
  });
})();</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>